### ISSUE TITLE
Fatal signal Segmentation fault caught in jsoniter-scala's unit tests when linking with `nativeLTO := "thin"`

### ISSUE THREAD

**Issue by plokhotnyuk** [cquiroz/sbt-tzdb#197]
```
[error] Fatal signal Segmentation fault caught
[error]   at scala.scalanative.testinterface.signalhandling.SignalConfig$.asyncSafePrintStackTrace(Unknown Source)
[error]   at <none>._SM70scala.scalanative.testinterface.signalhandling.SignalConfig$$$Lambda$1G17$extern$forwarder(Unknown Source)
[error]   at scala.scalanative.runtime.package$.throwClassCast(Unknown Source)
[error]   at java.time.zone.StandardZoneRules$.apply(Unknown Source)
[error]   at zonedb.java.tzdb$eurlt$.Europe_Malta$lzycompute(Unknown Source)
[error]   at zonedb.java.tzdb$.stdZones$lzycompute(Unknown Source)
[error]   at java.time.zone.TzdbZoneRulesProvider.provideZoneIds(Unknown Source)
[error]   at java.time.zone.ZoneRulesProvider$.registerProvider0(Unknown Source)
[error]   at java.time.zone.ZoneRulesProvider$.registerProvider(Unknown Source)
[error]   at java.time.zone.ServiceLoaderZoneRulesInitializer$$Lambda$3.apply(Unknown Source)
[error]   at java.time.zone.ServiceLoaderZoneRulesInitializer.initializeProviders(Unknown Source)
[error]   at java.time.zone.ZoneRulesInitializer$.initialize(Unknown Source)
[error]   at <none>._SM33java.time.zone.ZoneRulesProvider$G4load(Unknown Source)
[error]   at java.time.ZoneId$.getAvailableZoneIds(Unknown Source)
[error]   at com.github.plokhotnyuk.jsoniter_scala.core.GenUtils$.<init>(Unknown Source)
[error]   at <none>._SM52com.github.plokhotnyuk.jsoniter_scala.core.GenUtils$G4load(Unknown Source)
[error]   at com.github.plokhotnyuk.jsoniter_scala.core.JsonReaderSpec.$anonfun$new$25(Unknown Source)
[error]   at com.github.plokhotnyuk.jsoniter_scala.core.JsonReaderSpec$$Lambda$37.apply(Unknown Source)
[error]   at org.scalatest.OutcomeOf.outcomeOf(Unknown Source)
[error]   at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(Unknown Source)
[error]   at org.scalatest.SuperEngine.runTestImpl(Unknown Source)
[error]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Unknown Source)
[error]   at org.scalatest.SuperEngine$$Lambda$16.apply(Unknown Source)
[error]   at org.scalatest.SuperEngine.traverseSubNodes$1(Unknown Source)
[error]   at org.scalatest.SuperEngine.runTestsInBranch(Unknown Source)
[error]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Unknown Source)
[error]   at org.scalatest.SuperEngine$$Lambda$16.apply(Unknown Source)
[error]   at org.scalatest.SuperEngine.traverseSubNodes$1(Unknown Source)
[error]   at org.scalatest.SuperEngine.runTestsInBranch(Unknown Source)
[error]   at org.scalatest.SuperEngine.runTestsImpl(Unknown Source)
[error]   at org.scalatest.wordspec.AnyWordSpecLike.runTests(Unknown Source)
[error]   at org.scalatest.Suite.run(Unknown Source)
[error]   at org.scalatest.SuperEngine.runImpl(Unknown Source)
[error]   at org.scalatest.tools.TaskRunner.executionFuture(Unknown Source)
[error]   at org.scalatest.tools.TaskRunner.execute(Unknown Source)
[error]   at scala.scalanative.testinterface.TestAdapterBridge.$anonfun$executeFun$1(Unknown Source)
[error]   at scala.util.Try$.apply(Unknown Source)
[error]   at scala.scalanative.testinterface.common.RunMuxRPC.$anonfun$attach$2(Unknown Source)
[error]   at scala.concurrent.Future.$anonfun$flatMap$1(Unknown Source)
[error]   at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Unknown Source)
[error]   at scala.concurrent.impl.CallbackRunnable.run(Unknown Source)
[error]   at scala.scalanative.runtime.ExecutionContext$.loop(Unknown Source)
[error]   at scala.scalanative.runtime.package$.loop(Unknown Source)
[error]   at scala.scalanative.testinterface.NativeRPC.loop(Unknown Source)
[error]   at scala.scalanative.testinterface.TestMain$.main(Unknown Source)
[error]   at <none>.main(Unknown Source)
[error]   at <none>.__libc_start_main(Unknown Source)
[error]   at <none>._start(Unknown Source)
[error] Test runner interrupted by fatal signal 11
[warn] Force close java.lang.RuntimeException: Process /home/andriy/Projects/com/github/plokhotnyuk/jsoniter-scala/jsoniter-scala-core/native/target/scala-2.12/jsoniter-scala-core-test-out finished with non-zero value 139
```

**Comment by cquiroz** [comment]
I'm not really an expert on native. How can we reproduce this?
