### ISSUE TITLE
Better Files Issue

### ISSUE THREAD

**Issue by mlvn23** [cquiroz/sbt-tzdb#20]
I'm not sure why, but upgrading sbt-tzdb from 0.3.2 to 0.4.0 causes BetterFiles issues on my Play App. This is the only change I did on my build. I'm also using BetterFiles 0.3.8 so I can't think why there would be any conflict (not to mention this is a plug-in). Just reporting in case others sees it as well. I'm rolling back to 0.3.2 in the mean time.

This is the error I've seen:

```
Uncaught error from thread [play-dev-mode-akka.actor.default-dispatcher-2]: better.files.package$.FileOps(Ljava/io/File;)Lbetter/files/Implicits$FileOps;, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[play-dev-mode]
java.lang.NoSuchMethodError: better.files.package$.FileOps(Ljava/io/File;)Lbetter/files/Implicits$FileOps;
        at play.runsupport.Reloader.$anonfun$reload$3(Reloader.scala:513)
        at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:484)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:490)
        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
        at scala.collection.Iterator.foreach(Iterator.scala:941)
        at scala.collection.Iterator.foreach$(Iterator.scala:941)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
        at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:162)
        at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:160)
        at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1429)
        at play.runsupport.Reloader.$anonfun$reload$1(Reloader.scala:515)
        at play.runsupport.Reloader$$anon$1.run(Reloader.scala:58)
        at java.security.AccessController.doPrivileged(Native Method)
        at play.runsupport.Reloader$.play$runsupport$Reloader$$withReloaderContextClassLoader(Reloader.scala:64)
        at play.runsupport.Reloader.reload(Reloader.scala:501)
        at play.core.server.DevServerStart$$anon$1.get(DevServerStart.scala:143)
        at play.core.server.DevServerStart$.$anonfun$mainDev$2(DevServerStart.scala:258)
        at akka.actor.CoordinatedShutdown.$anonfun$run$3(CoordinatedShutdown.scala:487)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
        at scala.collection.Iterator.foreach(Iterator.scala:941)
        at scala.collection.Iterator.foreach$(Iterator.scala:941)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
        at scala.collection.IterableLike.foreach(IterableLike.scala:74)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
        at scala.collection.TraversableLike.map(TraversableLike.scala:238)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
        at scala.collection.AbstractTraversable.map(Traversable.scala:108)
        at akka.actor.CoordinatedShutdown.loop$1(CoordinatedShutdown.scala:484)
        at akka.actor.CoordinatedShutdown.$anonfun$run$6(CoordinatedShutdown.scala:530)
        at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:92)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:92)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:49)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by cquiroz** [comment]
I thought plugins' classloader were isolated from the project.
Maybe I should consider removing these dependencies

**Comment by mlvn23** [comment]
I thought so as well. I tried two versions of SBT 1.2.8 and 1.3.8, but I got the same results.

**Comment by cquiroz** [comment]
So plugins live on the same classloader than sbt
https://gitter.im/sbt/sbt?at=5e78eb3466919c3b2f840bc6
I always upgrade to the latest version and I'd expect other plugins to do the same

As an alternative you could split your tzdb generatioun to a separate project e.g:
https://github.com/gemini-hlsw/gemini-locales/

I'm going to close this one but I'd take PRs if somebody wants to do it

**Comment by mlvn23** [comment]
I've reproduced this issue on https://github.com/mlvn23/gemini-locales by adding the Play Framework SBT plugin.

've tried version 2.7.3, 2.7.4, and even with 2.8.1.

It fails at the Reloader.scala around line 510 in all cases. I see that they are using better.files around that line.

**Comment by cquiroz** [comment]
Does it make sense to ask play to upgrade?

**Comment by mlvn23** [comment]
They don't appear to have direct dependency using GitHub search. It might easier to roll back BetterFiles to 3.7.0 like in version 0.3.2?

**Comment by cquiroz** [comment]
That is certainly an approach that would work but I have other dependencies that can collide with n other plugins
The only rational logic for me is to use always the latest version and hope other plugins do the same

**Comment by cquiroz** [comment]
BTW the idea on gemini-locales is that I export that package as a binary and import it on my actual apps 
that approach not only would solve this but the build is a lot faster

**Comment by mlvn23** [comment]
Shading is another option. Or you can release note it that this is not compatible with certain Play versions.

**Comment by mlvn23** [comment]
Thanks, I'll give that a try.

**Comment by mlvn23** [comment]
Using it as an external lib solves this problem as well as another issue I saw wherein some directory in the generated files are getting locked and the only way to delete it is to shutdown sbt.

**Comment by mlvn23** [comment]
Sorry, the issue is still there:

```
[info] Generating tzdb from db at D:\extradash\code\src\jvm-lib\pathfinder-locale\target\scala-2.12\resource_managed\main\tzdb to D:\extradash\code\src\jvm-lib\pathfinder-locale\target\scala-2.12\src_managed\main
[error] java.lang.RuntimeException: Could not create directory D:\extradash\code\src\jvm-lib\pathfinder-locale\target\scala-2.12\resource_managed\main\locales\common\main
[error]         at scala.sys.package$.error(package.scala:26)
[error]         at sbt.io.IO$.createDirectory(IO.scala:326)
[error]         at sbt.io.IO$.next$1(IO.scala:400)
[error]         at sbt.io.IO$.extract(IO.scala:416)
[error]         at sbt.io.IO$.$anonfun$unzipStream$1(IO.scala:380)
[error]         at sbt.io.Using.apply(Using.scala:22)
[error]         at sbt.io.IO$.unzipStream(IO.scala:380)
[error]         at sbt.io.IO$.$anonfun$unzipURL$1(IO.scala:371)
[error]         at sbt.io.Using.apply(Using.scala:22)
[error]         at sbt.io.IO$.unzipURL(IO.scala:371)
[error]         at locales.IOTasks$.$anonfun$downloadCLDR$12(IOTasks.scala:32)
[error]         at cats.effect.internals.IORunLoop$.step(IORunLoop.scala:190)
[error]         at cats.effect.IO.unsafeRunTimed(IO.scala:321)
[error]         at cats.effect.IO.unsafeRunSync(IO.scala:240)
[error]         at locales.LocalesPlugin$.localesCodeGenImpl(LocalesPlugin.scala:89)
[error]         at locales.LocalesPlugin$autoImport$.$anonfun$baseLocalesSettings$4(LocalesPlugin.scala:55)
[error]         at sbt.util.FileFunction$.$anonfun$cached$1(FileFunction.scala:73)
[error]         at sbt.util.FileFunction$.$anonfun$cached$4(FileFunction.scala:147)
[error]         at sbt.util.Difference.apply(Tracked.scala:313)
[error]         at sbt.util.Difference.apply(Tracked.scala:293)
[error]         at sbt.util.FileFunction$.$anonfun$cached$3(FileFunction.scala:143)
[error]         at sbt.util.Difference.apply(Tracked.scala:313)
[error]         at sbt.util.Difference.apply(Tracked.scala:288)
[error]         at sbt.util.FileFunction$.$anonfun$cached$2(FileFunction.scala:142)
[error]         at locales.LocalesPlugin$autoImport$.$anonfun$baseLocalesSettings$3(LocalesPlugin.scala:58)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:278)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (Compile / localesCodeGen) Could not create directory D:\extradash\code\src\jvm-lib\pathfinder-locale\target\scala-2.12\resource_managed\main\locales\common\main
```
