### ISSUE TITLE
Not working with TZDB version 2018f onwards

### ISSUE THREAD

**Issue by rpiaggio** [cquiroz/sbt-tzdb#6]
Hi @cquiroz !

After a `clean` I started getting the following error with the latest TZDB version (2018g), which also happens with 2018f. With 2018e it works fine.

```
[error] java.time.DateTimeException: Invalid value for HourOfDay (valid values 0 - 23): 25
[error]         at java.time.temporal.ValueRange.checkValidValue(ValueRange.java:311)
[error]         at java.time.temporal.ChronoField.checkValidValue(ChronoField.java:703)
[error]         at java.time.LocalTime.of(LocalTime.java:296)
[error]         at kuyfi.TZDBParser$.$anonfun$hourMinParserLT$1(TZDBParser.scala:118)
[error]         at atto.Parser$$anon$5.$anonfun$apply$5(Parser.scala:29)
[error]         at cats.Eval$.advance(Eval.scala:272)
[error]         at cats.Eval$.loop$1(Eval.scala:354)
[error]         at cats.Eval$.cats$Eval$$evaluate(Eval.scala:372)
[error]         at cats.Eval$Defer.value(Eval.scala:258)
[error]         at atto.ParserFunctions.parseOnly(Parser.scala:102)
[error]         at atto.ParserFunctions.parseOnly$(Parser.scala:99)
[error]         at atto.Parser$.parseOnly(Parser.scala:42)
[error]         at atto.syntax.ParserOps.parseOnly(ParserOps.scala:19)
[error]         at atto.syntax.ParserOps.parseOnly$(ParserOps.scala:18)
[error]         at atto.syntax.ToParserOps$$anon$1.parseOnly(ParserOps.scala:99)
[error]         at kuyfi.TZDBParser$.parseFile(TZDBParser.scala:256)
[error]         at kuyfi.TZDBParser$.$anonfun$parseAll$3(TZDBParser.scala:293)
[error]         at scala.collection.Iterator$$anon$10.next(Iterator.scala:457)
[error]         at scala.collection.Iterator.foreach(Iterator.scala:944)
[error]         at scala.collection.Iterator.foreach$(Iterator.scala:944)
[error]         at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
[error]         at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:59)
[error]         at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:50)
[error]         at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:186)
[error]         at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:44)
[error]         at scala.collection.TraversableOnce.to(TraversableOnce.scala:310)
[error]         at scala.collection.TraversableOnce.to$(TraversableOnce.scala:308)
[error]         at scala.collection.AbstractIterator.to(Iterator.scala:1432)
[error]         at scala.collection.TraversableOnce.toList(TraversableOnce.scala:294)
[error]         at scala.collection.TraversableOnce.toList$(TraversableOnce.scala:294)
[error]         at scala.collection.AbstractIterator.toList(Iterator.scala:1432)
[error]         at kuyfi.TZDBParser$.$anonfun$parseAll$1(TZDBParser.scala:294)
[error]         at cats.effect.internals.IORunLoop$.step(IORunLoop.scala:167)
[error]         at cats.effect.IO.unsafeRunTimed(IO.scala:307)
[error]         at cats.effect.IO.unsafeRunSync(IO.scala:242)
[error]         at io.gitub.sbt.tzdb.TzdbPlugin$.tzdbCodeGenImpl(SbtTzdb.scala:79)
[error]         at io.gitub.sbt.tzdb.TzdbPlugin$.$anonfun$projectSettings$3(SbtTzdb.scala:60)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:278)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error]         at java.lang.Thread.run(Thread.java:748)
```

**Comment by cquiroz** [comment]
Did you try the very latest version `0.3.0`. This should have been fixed

**Comment by cquiroz** [comment]
Not really but I'll update the readme
